# Relevant file/directory paths
PATHS:
  RAW_DATA: 'data/raw/HIFIS_Clients.csv'
  PROCESSED_DATA: 'data/processed/HIFIS_Processed.csv'
  PROCESSED_OHE_DATA: 'data/processed/HIFIS_Processed_OHE.csv'
  GROUND_TRUTH: 'data/processed/GroundTruth.csv'
  INTERPRETABILITY: './data/interpretability/feature_info.yml'
  MODEL_WEIGHTS: 'results/models/model.h5'
  IMAGES: 'documents/images/'
  LOGS: 'results\\logs\\'
  HORIZON_SEARCH: 'results/experiments/horizon_search.csv'
  TRAIN_SET: 'data/processed/Train_Set.csv'
  TEST_SET: 'data/processed/Test_Set.csv'
  SCALER_COL_TRANSFORMER: 'data/transformers/scaler_col_transformer.bin'
  ORDINAL_COL_TRANSFORMER: 'data/transformers/ordinal_col_transformer.bin'
  OHE_COL_TRANSFORMER: 'data/transformers/ohe_col_transformer.bin'

# Constants pertaining to data structure
DATA:
  N_WEEKS: 4
  N_MIN: 0
  N_MAX: 52
  N_INTERVAL: 4
  GROUND_TRUTH_DATE: '2020-01-09'
  CHRONIC_THRESHOLD: 180
  FEATURES_TO_DROP_FIRST: ['OrganizationID','DOB','MovedInDate']
  FEATURES_TO_DROP_LAST: ['ServiceID','FamilyID','ServiceEndDate','ExpenseStartDate','ExpenseEndDate','IncomeStartDate',
                          'IncomeEndDate','HealthIssueStart','HealthIssueEnd','LifeEventStartDate','LifeEventEndDate','SPDAT_Date', 'MonthlyAmount',
                          'ContributingFactorDateStart','ContributingFactorDateEnd','BehavioralRiskFactorDateStart','BehavioralRiskFactorDateEnd',
                          'EducationStartDate','EducationEndDate']
  TIMED_SERVICE_FEATURES: ['Stay']
  COUNTED_SERVICE_FEATURES: ['Housing Loss Prevention', 'Housing Subsidy', 'Reservations', 'Turnaways', 'Food Bank']
  NONCATEGORICAL_FEATURES: ['ServiceID','ClientID','FamilyID','ServiceStartDate', 'ServiceEndDate','CurrentAge','ClientHeightCM',
    'ClientWeightKG','MonthlyAmount', 'ExpenseAmount','SPDAT_Date','TotalScore']
  CATEGORICAL_FEATURES: ['ConsentType', 'RelationshipType', 'Gender', 'AboriginalIndicator', 'Citizenship', 'VeteranStatus', 'CountryOfBirth',
    'ProvinceOfBirth', 'CityOfBirth', 'GeoRegion', 'HairColour', 'EyeColour', 'ServiceType', 'OrganizationName', 'ReasonForService',
    'CurrentlyHoused', 'IncomeType', 'ExpenseType', 'Expensefrequency', 'IsEssentialYN', 'EducationLevel', 'HealthIssue', 'DiagnosedYN',
    'SelfReportedYN', 'SuspectedYN', 'HealthIssueMedicationName', 'OtherMedications', 'WatchConcern', 'ContributingFactor', 'BehavioralFactor',
    'Severity', 'LifeEvent', 'DietCatetory', 'FoodType', 'AvoidInDiet', 'SPDAT_Type', 'ServiceProvider', 'PreScreenPeriod']
  TIME_PAIRED_FEATURES:
    -
      NAME: 'Service'
      START: 'ServiceStartDate'
      END: 'ServiceEndDate'
  OTHER_TIMED_FEATURES:
      ExpenseStartDate: ['ExpenseType', 'Expensefrequency', 'ExpenseAmount', 'IsEssentialYN']
      IncomeStartDate: ['IncomeType', 'MonthlyAmount']
      HealthIssueStart: ['HealthIssue', 'HealthIssueMedicationName', 'OtherMedications', 'DiagnosedYN','SelfReportedYN', 'SuspectedYN']
      ContributingFactorDateStart: ['ContributingFactor']
      BehavioralRiskFactorDateStart: ['BehavioralFactor', 'Severity']
      LifeEventStartDate: ['LifeEvent']
      SPDAT_Date: ['TotalScore']


# Neural network models
NN:
  MODEL1:
    NODES:
      DENSE0: 100
      DENSE1: 100
    L2_LAMBDA: 0.01
    DROPOUT: 0.3

# Training
TRAIN:
  TRAIN_SPLIT: 0.8
  VAL_SPLIT: 0.1
  TEST_SPLIT: 0.1
  EPOCHS: 100
  BATCH_SIZE: 128
  CLASS_WEIGHT: true
  MINORITY_OVERSAMPLE: false
  RUNS_PER_N: 100